### ISSUE TITLE
笔误

### ISSUE THREAD

**Issue by xuyang2** [ArthurChiao/arthurchiao.github.io#10]
https://github.com/ArthurChiao/arthurchiao.github.io/blob/9b23cfa6f70768b30aace01ea1579913f91094e0/_posts/2021-10-07-everything-about-pki-zh.md?plain=1#L1042

一旦理解了背后的原理

https://github.com/ArthurChiao/arthurchiao.github.io/blob/9b23cfa6f70768b30aace01ea1579913f91094e0/_posts/2021-10-07-everything-about-pki-zh.md?plain=1#L1086

 一个证书可以有多个 SAN

**Comment by ArthurChiao** [comment]
感谢指正，已修改。
