### ISSUE TITLE
输入法联想错误

### ISSUE THREAD

**Issue by lanthora** [ArthurChiao/arthurchiao.github.io#11]
输入法联想错误,应该为"事件"

https://github.com/ArthurChiao/arthurchiao.github.io/blob/6ea40058223551b722ee58ce4bc6d985f42556f8/_posts/2022-04-24-bpf-ringbuf-zh.md?plain=1#L330

**Comment by ArthurChiao** [comment]
笔误，感谢指正，有空改一下！ @lanthora
