### ISSUE TITLE
tc-egress的执行阶段

### ISSUE THREAD

**Issue by taoyuanyuan** [ArthurChiao/arthurchiao.github.io#13]
https://github.com/ArthurChiao/arthurchiao.github.io/blob/master/assets/code/cracking-k8s-node-proxy/bpf/toy-proxy-bpf.c
请教一个问题，tc-egress应该是在route和neighbor之后了，如果在这个阶段改了目标ip，还会重新走route，更新mac地址吗？

**Comment by ArthurChiao** [comment]
Hi 不会的，更新 IP + checksum 之后就直接发出去了。实际上（对于本文这种直接路由场景）dst mac 是宿主机网关的 mac 地址，所以不需要更新。

**Comment by taoyuanyuan** [comment]
感谢回复，看到有个bpf_fib_lookup的helper，感觉也可以自己重新设置mac

**Comment by ArthurChiao** [comment]
对的，可以的。
