### ISSUE TITLE
翻译问题~此处应该是公钥吧

### ISSUE THREAD

**Issue by LiZhongChen0073** [ArthurChiao/arthurchiao.github.io#16]
https://github.com/ArthurChiao/arthurchiao.github.io/blob/b1cac0ad01a38eab454a85fa27ce631dfff92d04/_posts/2021-10-07-everything-about-pki-zh.md?plain=1#L306
![image](https://user-images.githubusercontent.com/86286812/230847353-393d8cfa-616b-47e9-8cb4-eee06aba68ba.png)
![image](https://user-images.githubusercontent.com/86286812/230847477-61613d67-bd11-4367-9dcf-9d9e233638fb.png)

**Comment by ArthurChiao** [comment]
是的，感谢指正：） @LiZhongChen0073
