### ISSUE TITLE
请教下混合部署容器场景下，限速的问题

### ISSUE THREAD

**Issue by forsakening** [ArthurChiao/arthurchiao.github.io#18]
hi，你好，请教下大数据和在线业务容器混合部署场景下，大数据容器的网络限速有什么好的方案吗？我们想使用tc，但是tc存在一个共享锁的问题，软中断过高的话可能会影响其他正常容器的重传、延迟、P99等问题。

**Comment by ArthurChiao** [comment]
@forsakening  不好意思，刚注意到。Issue 只用来跟踪 repo 本身问题。技术交流请发邮件到个人邮箱（主页上有），谢谢！
