### ISSUE TITLE
script sources

### ISSUE THREAD

**Issue by Tanganelli** [ArthurChiao/arthurchiao.github.io#2]
Hi,
I am really interested in the article OVS Deep Dive 6: Internal Port. Can you share the mentioned scripts? 
1 - ./expose_container_netns.sh 
2 - ./add-tap-to-container.sh

Thanks in advance
Giacomo

**Comment by ArthurChiao** [comment]
Hi @Tanganelli, thanks for reminding, missing scripts added.

By the way, `nsenter` is more flexible than my `expose_container_netns.sh`, I've added an **UPDATE** section in the post for introducing this.
