### ISSUE TITLE
BGP in the Data Center 文章中发现一处小错误

### ISSUE THREAD

**Issue by xdai555** [ArthurChiao/arthurchiao.github.io#6]
在 [3.5小节](https://github.com/ArthurChiao/arthurchiao.github.io/blob/go/_posts/2019-04-01-bgp-in-data-center-zh.md#chap_3.5) 中：

> 注意：建议所有变量使用小写.....

这里应该是大写，我看了下原文是 `all caps` 。

> Just about every network configuration I’ve seen uses all caps for route-map and prefix-list names.

**Comment by ArthurChiao** [comment]
多谢指正，有空我改一下：） @xdai555

**Comment by ArthurChiao** [comment]
Done.
