### ISSUE TITLE
https://arthurchiao.github.io/ 打不开了

### ISSUE THREAD

**Issue by danerlt** [ArthurChiao/arthurchiao.github.io#9]
博客,首页左下角点击[Arthur Chiao] 会跳转到 https://arthurchiao.github.io/ , 这个域名打不开,建议换成你的github地址或者这个项目的github地址

**Comment by ArthurChiao** [comment]
感谢反馈！ 这个域名是 github 自动生成的，国内访问可能时好时坏，后面我改下地址，谢谢！ @danerlt
